# Generated by Django 4.2.10 on 2024-02-13 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_date_published_book_goodreads_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='goodreads_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
