# Generated by Django 4.2.10 on 2024-02-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_options_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default='English', help_text="Enter the book's natural language (e.g. English, French, Japanese, etc.)", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
